### ISSUE TITLE
Compatibility with other game

### ISSUE THREAD

**Issue by Tfausx** [marcussacana/MwareStuff#2]
Hi marcus! Thanks so much for this tool! Me and my team was wondering if there's a possibilty to make it compatible with the visual novel "Minikui Mojika no Ko", uses the same Nitroplus engine!

Thanks in advance!

**Comment by marcussacana** [comment]
Test it, if everything works, close this issue.

**Comment by Tfausx** [comment]
thanks, everything works perfect on Tokyo Necro -unpack / pack -, but in Minikui Mojika no Ko, the scripts text seems to be bad (i tried to edit him and compress again with your nut editor but game crashes), i attached an image of the text:

https://i.ibb.co/nbbznxV/1.png

That PAD code doesn't appears on Tokyo Necro - Totono texts

Cheers and thanks for your help!

**Comment by marcussacana** [comment]
I saw that before, but you take a look in the plugin manager?
We have 2 versions of the NUTEditor now, and one of then should fix this problem.

**Comment by Tfausx** [comment]
I tested both versions of the NUTeditor, still have the same problem, game crash on repack and the text still seems like the picture i posted above

**Comment by marcussacana** [comment]
hmm let'me check then

**Comment by marcussacana** [comment]
The problem isn't with the NUTEditor, is a problem of the NPK3Tool;
Also, your file is corrupted is because your text editor isn't reading the UTF8 txt or you installed the wrong NUTEditor plugin (I Recommend keep only one of both installed at the same time)

**Comment by Tfausx** [comment]
all works flawlessly now, thank you very much! God bless you and have a nice day!
